dist: xenial
language: python
python:
  - "3.6"
  - "3.7"
jdk:
  - openjdk8
# command to install services
services:
  - elasticsearch
# command to install dependencies
before_install:
  - pip install poetry
install:
  - poetry install
before_script:
  - sleep 15
# command to run tests
script:
  - ./lintme
  - travis_wait 30 poetry run mindmeld num-parse
  - mkdir ~/test-reports
  - travis_wait 30 poetry run pytest --junitxml=~/test-reports/junit.xml --cov-report html --cov=webex_assistant_sdk